=== IMAGE-ET/mediboard-legacy/document.dtd
<!ELEMENT note (de, a+, sujet, CMU, contenu, attache*, postscriptum?)>

<!ELEMENT de (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ELEMENT sujet (#PCDATA)>
<!ELEMENT CMU (yes|no)>
<!ELEMENT contenu (#PCDATA)>
<!ELEMENT postscriptum (#PCDATA)>
<!ELEMENT attache EMPTY>

<!ELEMENT yes EMPTY>
<!ELEMENT no EMPTY>

<!ATTLIST note date NMTOKEN #IMPLIED>
<!ATTLIST attache url CDATA #REQUIRED>

=== IMAGE-ET/mediboard-legacy/document.xml
<?xml version="1.0" ?>
<!DOCTYPE note SYSTEM "document.dtd">
<note date="02-02-2005">
<de/>
<a>Lucrèce</a>
<a>Joséphine</a>
<sujet>Rappel</sujet>
<CMU>
<yes />
</CMU>
<contenu>
N'oublie pas la fête de fin d'exams!
</contenu>
<attache url="http://www.party.com/flyer.jpg"/>
</note>
